service: notions-tasks

provider:
  name: google
  stage: dev
  runtime: nodejs16
  region: us-central1
  project: notion-daily-todo-list
  # The GCF credentials can be a little tricky to set up. Luckily we've documented this for you here:
  # https://serverless.com/framework/docs/providers/google/guide/credentials/
  #
  # the path to the credentials file needs to be absolute
  credentials: ~/.config/gcloud/application_default_credentials.json

frameworkVersion: '3'

plugins:
  - serverless-google-cloudfunctions
  - serverless-plugin-typescript

# needs more granular excluding in production as only the serverless provider npm
# package should be excluded (and not the whole node_modules directory)
package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**
    - tsconfig.json
    - .build
  excludeDevDependencies: true

functions:
  first:
    handler: archiveTasksNotion
    events:
      - event:
          eventType: providers/cloud.pubsub/eventTypes/topic.publish
          resource: projects/notion-daily-todo-list/topics/cron-topic

